user_agent_list = [
    # Chrome
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',
    'Mozilla/5.0 (Windows NT 5.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.2; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.90 Safari/537.36',
    'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.113 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36',
    # Firefox
    'Mozilla/4.0 (compatible; MSIE 9.0; Windows NT 6.1)',
    'Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 6.1; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 6.2; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.0; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)',
    'Mozilla/5.0 (Windows NT 6.1; Win64; x64; Trident/7.0; rv:11.0) like Gecko',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0)',
    'Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; Trident/6.0)',
    'Mozilla/4.0 (compatible; MSIE 8.0; Windows NT 5.1; Trident/4.0; .NET CLR 2.0.50727; .NET CLR 3.0.4506.2152; .NET CLR 3.5.30729)'
]


nameFilter = ["tarifi", "video", "videolu", "nasıl", "yapılır", "nefis",
              "enfes", "şahane", "mükemmel", "lezzet", "lezzetli", "sahur"
              "özel", "mis", "gibi", "videosu", "mutlaka", "deneyin",
              "anlatım", "çok", "tane", "teremyağ", "teremyağlı", "sana",
              "sanalı", "ustasından", "eller", "usta", "meşhur", "bol",
              "vitaminli", "vitamin", "usulü", "annem", "annemin",
              "annem'in", "kolay", "yapımı", "el", "ağızda", "dağılan"]


ingredientFilter = ["kaşığı", "tatlı", "çorba", "tutam", "bir", "iki",
                    "kulak", "memesi", "gr", "kg", "yarım", "tam",
                    "yemek", "arzunuza", "göre", "arzu", "damak",
                    "zevkinize", "zevkine", "yaprak", "çay", "bardağı",
                    "diş", "yağlı", "yağsız", "çekilmiş", "sinirsiz",
                    "kere", "çeyrek", "baş", "salkım", "çay", "yaprakları",
                    "demet", "paket", "isteğe", "dal", "adet", "kurumuş",
                    "yaklaşık", "eksik", "az", "bardağından", "su", "isteğe",
                    "bağlı", "istenilen", "kadar", "lt", "soğuk", "sıcak",
                    "tepeleme", "kilo", "gram", "litre", "ince", "kalın",
                    "kilogram", "kase", "çırpılmış", "orta", "boy", "biraz",
                    "rende", "rendelenmiş", "rendesi", "dilim", "kaşık",
                    "tane", "büyük", "küçük", "aldığı", "bardak", "fincan",
                    "buçuk", "ml", "mililitre", "mili", "kaynar", "bi",
                    "üç", "ve", "önceden", "birazcık", "haşlanmış",
                    "göz", "kararı", "defa", "", " ", "dövülmüş",
                    "yağsızsinirsiz", "kişi", "sayısına", "göre", "ne",
                    "istiyorsanız", "olmasını", "salçanın", "tuzluluğuna",
                    "tuzluluğu", "tuzlu", "ıslamak", "ıslatmak", "için",
                    "üste", "üstüne", "sürülecek", "sürülmeli", "farketmez",
                    "ayrılacak", "ayrılmalı", "inin", "kesilmiş", "sıcağa",
                    "yakın", "ılık", "sıcak", "soğuk", "kıvama", "ekleyin",
                    "canınız", "isterse", "ekleyebilirsiniz", "kaşıgı",
                    "kare", "üçgen", "dikdörtgen", "yuvarlak", "kibrit",
                    "kutusu", "ince", "doğranmış", "kısmından", "kararı",
                    "istenilen", "miktarda", "çimdik", "saf", "süsleme",
                    "süslemek", "istediğiniz", "gibi", "süsleyebilirsiniz",
                    "beyazı", "parça", "renkli", "birazda", "kaşığının",
                    "kaşığını", "ucuyla", "kıyım", "servis", "kasığı",
                    "kaşığına", "yeteri", "bağ", "eritilmiş", "oda",
                    "sıcaklığında", "bol", "yarısı", "çeyreği", "küçükorta",
                    "cimdik", "alabildiği", "alabildiğine", "fincanı",
                    "tepeli", "yeterince"]
